# This workflow will automatically update an old Robinhood OAuth token with a new one if necessary
# For more information see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

name: Daily Update

on:
  schedule:
    - cron: "0 0,12 * * *"

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Decrypt token
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: scripts/decrypt.sh

      - name: Update token
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python scripts/login.py

      - name: Encrypt token
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: scripts/encrypt.sh

      - name: Commit token
        uses: stefanzweifel/git-auto-commit-action@v4.4.0
        with:
          file_pattern: robinhood.pickle.gpg
          commit_message: "[AUTO] OAuth token refresh #patch"
          commit_user_name: suchak1
          commit_user_email: suchak.krish@gmail.com
          commit_author: Krish Suchak
          push_options: "--force"
